# Site settings
title: Crowder
email: contact@crowderapp.com
description: > # this means to ignore newlines until "baseurl:"
 Crowder’s where you start and find nearby crowds, see what the crowds are doing, see who’s in those crowds, and how many people are in them at the moment

baseurl: "" # the subpath of your site, e.g. /blog/
url: "crowderapp.com" # the base hostname & protocol for your site

twitter_username: crowder_tweets
github_username:  eorroe

# Build settings
markdown: kramdown
